" General
colors zenburn
set number
set linebreak
set showbreak=+++ 
set textwidth=80
set showmatch
set spell
set visualbell
 
set hlsearch
set smartcase
set ignorecase
set incsearch
 
set autoindent
set expandtab
set shiftwidth=4
set smartindent
set smarttab
set softtabstop=4
 
" Advanced
set ruler
 
set undolevels=1000
set backspace=indent,eol,start
 
 
" Generated by VimConfig.com

au FileType html setl sw=2 sts=2
